name = "POD_LES"
uuid = "149de816-399e-497f-875a-ddff1c8001eb"
authors = ["tobyvg <tobyvangastelen@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
